<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LT0217181" failures="1" tests="5" name="Forward ordering flow" time="59.986" errors="0" timestamp="2024-06-24T15:56:06 IST">
  <testcase classname="SeleniumJava.TestNgFramework.standaloneFrameWork" name="submitOrder" time="11.249"/>
  <testcase classname="SeleniumJava.TestNgFramework.standaloneFrameWork" name="submitOrder" time="11.162"/>
  <testcase classname="SeleniumJava.TestNgFramework.standaloneFrameWork" name="orderDetailsValidation" time="4.556">
    <skipped/>
  </testcase> <!-- orderDetailsValidation -->
  <testcase classname="SeleniumJava.TestNgFramework.standaloneFrameWork" name="orderDetailsValidation" time="4.588">
    <skipped/>
  </testcase> <!-- orderDetailsValidation -->
  <testcase classname="SeleniumJava.TestNgFramework.standaloneFrameWork" name="orderDetailsValidation" time="4.559">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at SeleniumJava.TestNgFramework.standaloneFrameWork.orderDetailsValidation(standaloneFrameWork.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- orderDetailsValidation -->
</testsuite> <!-- Forward ordering flow -->
